(defproject clojuretoml "1.0.0"
  :description "toms test clojure project"
  :min-lein-version "2.7.1"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [http-kit "2.2.0"]
                 [clj-time "0.14.0"]
                 [com.cemerick/friend "0.1.5" :exclusions [ring/ring-core]]
                 [ring-server "0.2.7"]
                 [ring/ring-json "0.5.0"]
                 [ring-middleware-format "0.7.4"]
                 [ring-cors "0.1.13"]
                 [http-kit "2.3.0"]
                 [ring/ring-defaults "0.3.2"]
                 [compojure "1.6.0"]
                 [com.taoensso/faraday "1.11.1"]
                 [compojure "1.6.1"]
                 [http-kit "2.5.0"]
                 [juxt/crux-core "20.09-1.12.1-beta"]
                 [com.novemberain/monger "3.1.0"]
                 [ring/ring-defaults "0.3.2"]
                 [metosin/ring-http-response "0.9.1"]
                 [org.clojure/core.async "1.3.610"]
                 [ring/ring-json "0.5.0"]
                 [org.apache.httpcomponents/httpclient "4.5.9"]
                 [org.apache.httpcomponents/httpcore "4.4.11"]
                 [com.amazonaws/aws-java-sdk-dynamodb "1.11.664"]
                 [org.clojure/data.json "1.0.0"]
                 [ring/ring-anti-forgery "1.3.0"]]
  :main clojuretoml.core)
